app:
    resource: '@AdminBundle/Action/'
    type: annotation

app_controller:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api'

# doc:
#     resource: '@ApiPlatformBundle/Resources/config/routing/swagger-ui.xml'

api_login_check:
    path: '/api/login_check'

admin:
    resource: '@AdminBundle/Controller/'
    type: 'annotation'

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
    prefix: /v1

fos_user_group:
    resource: '@FOSUserBundle/Resources/config/routing/group.xml'
    prefix: /v1/group

easy_admin_bundle:
    resource: '@AdminBundle/Controller/AdminController.php'
    type: annotation
    prefix: /v1/easyadmin

liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'
    prefix: /v1

terms_bundle:
    resource: '@ItkDevTermsBundle/Resources/config/routing.xml'
    prefix: /v1/terms
