<?php

/*
 * This file is part of Eventbase API.
 *
 * (c) 2017–2018 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace Tests\AppBundle\Test;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * @coversNothing
 */
class DatabaseWebTestCase extends WebTestCase
{
    /**
     * @var EntityManagerInterface
     */
    protected static $em;

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass();

        //    $kernel = static::createKernel();
        //    $kernel->boot();
        //    $em = $kernel->getContainer()->get('doctrine')->getManager();
        static::bootKernel();
        static::$em = static::$kernel->getContainer()->get('doctrine')->getManager();
        $schemaTool = new SchemaTool(static::$em);
        $metadata = static::$em->getMetadataFactory()->getAllMetadata();

        // Drop and recreate tables for all entities
        $schemaTool->dropSchema($metadata);
        $schemaTool->createSchema($metadata);
        $schemaTool->updateSchema($metadata);
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub

        return;
        $kernel = static::createKernel();
        $purger = new ORMPurger($kernel->getContainer()->get('doctrine')->getManager());
        $purger->setPurgeMode(ORMPurger::PURGE_MODE_TRUNCATE);
        $purger->purge();
    }
}
