on: pull_request
name: Review
jobs:
    test-composer-install:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["7.2", "7.4"]
        name: Validate composer (PHP ${{ matrix.php}})
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none
                  tools: composer:v1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Validate composer files
              run: composer validate composer.json --strict

            - name: '[dev] Composer install'
              run: composer install -n --prefer-dist

    validate-doctrine-schema:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: mysql://db:db@127.0.0.1:3306/db?serverVersion=mariadb-10.5.0
        strategy:
            fail-fast: false
            matrix:
                php: ["7.2"]
        name: Validate Doctrine Schema (PHP ${{ matrix.php}})
        services:
            mariadb:
                image: mariadb:10.5
                env:
                    MYSQL_USER: db
                    MYSQL_PASSWORD: db
                    MYSQL_DATABASE: db
                    MYSQL_ROOT_PASSWORD: db
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none
                  tools: composer:v1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: '[dev] Composer install'
              run: composer install --no-interaction --prefer-dist

            - name: Run Doctrine Migrations
              run: php bin/console doctrine:migrations:migrate --no-interaction

            - name: Validate Doctrine schema
              run: php bin/console doctrine:schema:validate

    phpunit:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                ports:
                    - 3306
                env:
                    MYSQL_USER: db
                    MYSQL_PASSWORD: db
                    MYSQL_DATABASE: db_test
                    MYSQL_ROOT_PASSWORD: password
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        strategy:
            fail-fast: false
            matrix:
                php: ["7.2"]
        name: PHP Unit tests (PHP ${{ matrix.php }})
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none
                  tools: composer:v1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install --no-interaction --prefer-dist

            - name: PHP Unit
              env:
                  PORT: ${{ job.services.mariadb.ports[3306] }}
              run: vendor/bin/phpunit

    behat:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                ports:
                    - 3306
                env:
                    MYSQL_USER: db
                    MYSQL_PASSWORD: db
                    MYSQL_DATABASE: db_test
                    MYSQL_ROOT_PASSWORD: password
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        strategy:
            fail-fast: false
            matrix:
                php: ["7.2"]
        name: PHP Unit tests (PHP ${{ matrix.php }})
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none
                  tools: composer:v1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install --no-interaction --prefer-dist

            - name: JWT Setup
              run: |
                mkdir -p var/jwt
                openssl genrsa -out var/jwt/private.pem -aes256 -passout pass:test 4096
                openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem -passin pass:test

            - name: Behat
              env:
                  PORT: ${{ job.services.mariadb.ports[3306] }}
              run: vendor/bin/behat

    apispec:
        runs-on: ubuntu-latest
        name: API Specification validation
        strategy:
            fail-fast: false
            matrix:
                php: ["7.2"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php}}
                  extensions: apcu, ctype, iconv, imagick, json, redis, soap, xmlreader, zip
                  coverage: none
                  tools: composer:v1

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ matrix.php }}-composer-

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            - name: Export specifications (yaml)
              run: bin/console api:swagger:export --output=public/api-spec-v1.json --no-interaction

            - name: Check for changes in specifications (yaml)
              run: git diff --diff-filter=ACMRT --exit-code public/api-spec-v1.json
